/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

import Business.Patient;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Vivek
 */
public class CreatePersonJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJpanel
     */
    
    Patient patient;
    Color defaultcolor;
    public CreatePersonJpanel(Patient patient) {
        initComponents();
        this.patient = patient;
        defaultcolor = patientnamejTextField.getBackground();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientnamejTextField = new javax.swing.JTextField();
        patientidjTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        doctornamejTextField = new javax.swing.JTextField();
        pharmacyjTextField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PERSON DATA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Patient Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Doctor Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pharmacy");

        patientnamejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                patientnamejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientnamejTextFieldFocusLost(evt);
            }
        });
        patientnamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientnamejTextFieldKeyTyped(evt);
            }
        });

        patientidjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                patientidjTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                patientidjTextFieldFocusLost(evt);
            }
        });

        agejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                agejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                agejTextFieldFocusLost(evt);
            }
        });
        agejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agejTextFieldKeyTyped(evt);
            }
        });

        doctornamejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doctornamejTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doctornamejTextFieldFocusLost(evt);
            }
        });
        doctornamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doctornamejTextFieldKeyTyped(evt);
            }
        });

        pharmacyjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pharmacyjTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pharmacyjTextFieldFocusLost(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(submitBtn)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addGap(139, 139, 139))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
       
        try{
        boolean flag=false;
        JTextField[] textFields = new JTextField[5];
        textFields[0] = patientnamejTextField;
        textFields[1] = patientidjTextField;
        textFields[2] = agejTextField;
        textFields[3] = doctornamejTextField;
        textFields[4] = pharmacyjTextField;
        
        if(agejTextField.getText().equals("0")){
            flag=false;
            JOptionPane.showMessageDialog(this, "Age cannot be zero","Warning",JOptionPane.WARNING_MESSAGE);
        } else {
            for(int i=0;i<5;i++) {
                if (textFields[i].getText().equals("")) {
                    flag=false;
                    JOptionPane.showMessageDialog(this, "Please fill all the fields","Warning",JOptionPane.WARNING_MESSAGE);
                    break;
                } else 
                {
                    flag=true;
                }}
        }
        if (flag){
        patient.setPatientName(patientnamejTextField.getText());
        patient.setPatentId(patientidjTextField.getText());
        patient.setAge(Integer.parseInt(agejTextField.getText()));
        patient.setDoctorName(doctornamejTextField.getText());
        patient.setPharmacy(pharmacyjTextField.getText());
        JOptionPane.showMessageDialog(this, "Data is been saved.");
        clearfields();
        }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Please specify the correct value. Exception throw!!");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void patientnamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientnamejTextFieldKeyTyped
        patientnamejTextField.setTransferHandler(null);
        char patientname = evt.getKeyChar();
        if (!(Character.isLetter(patientname) || patientname==' '))
                evt.consume();         
        
    }//GEN-LAST:event_patientnamejTextFieldKeyTyped

    private void agejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agejTextFieldKeyTyped
        agejTextField.setTransferHandler(null);
        char age = evt.getKeyChar();
        if (!(Character.isDigit(age)))
                evt.consume();
    }//GEN-LAST:event_agejTextFieldKeyTyped

    private void doctornamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doctornamejTextFieldKeyTyped
        doctornamejTextField.setTransferHandler(null);
        char doctorname = evt.getKeyChar();
        if (!(Character.isLetter(doctorname) || doctorname==' '))
                evt.consume();           
        
    }//GEN-LAST:event_doctornamejTextFieldKeyTyped

    private void patientnamejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientnamejTextFieldFocusGained
        patientnamejTextField.setBackground(Color.yellow);
    }//GEN-LAST:event_patientnamejTextFieldFocusGained

    private void patientnamejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientnamejTextFieldFocusLost
        patientnamejTextField.setBackground(defaultcolor);
        
    }//GEN-LAST:event_patientnamejTextFieldFocusLost

    private void patientidjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientidjTextFieldFocusGained
        patientidjTextField.setBackground(Color.yellow);
    }//GEN-LAST:event_patientidjTextFieldFocusGained

    private void patientidjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patientidjTextFieldFocusLost
        patientidjTextField.setBackground(defaultcolor);            
    }//GEN-LAST:event_patientidjTextFieldFocusLost

    private void agejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agejTextFieldFocusGained
        agejTextField.setBackground(Color.yellow);
    }//GEN-LAST:event_agejTextFieldFocusGained

    private void agejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agejTextFieldFocusLost
        agejTextField.setBackground(defaultcolor);
    }//GEN-LAST:event_agejTextFieldFocusLost

    private void doctornamejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doctornamejTextFieldFocusGained
        doctornamejTextField.setBackground(Color.yellow);
    }//GEN-LAST:event_doctornamejTextFieldFocusGained

    private void doctornamejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doctornamejTextFieldFocusLost
        doctornamejTextField.setBackground(defaultcolor);        
    }//GEN-LAST:event_doctornamejTextFieldFocusLost

    private void pharmacyjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pharmacyjTextFieldFocusGained
        pharmacyjTextField.setBackground(Color.yellow);
    }//GEN-LAST:event_pharmacyjTextFieldFocusGained

    private void pharmacyjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pharmacyjTextFieldFocusLost
        pharmacyjTextField.setBackground(defaultcolor);
    }//GEN-LAST:event_pharmacyjTextFieldFocusLost
    
    public void clearfields()
    {
        patientnamejTextField.setText("");
        patientidjTextField.setText("");
        agejTextField.setText("");
        doctornamejTextField.setText("");
        pharmacyjTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agejTextField;
    private javax.swing.JTextField doctornamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patientidjTextField;
    private javax.swing.JTextField patientnamejTextField;
    private javax.swing.JTextField pharmacyjTextField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
