/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

import Business.Patient;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class ViewjPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewjPanel
     */
    
    private VitalSignHistory vitalsignhistory;
    Patient pat; 
    int age;
    public static boolean status=true;
    
    public ViewjPanel(VitalSignHistory vitalsignhistory, Patient patient) {
        initComponents();
        this.vitalsignhistory = vitalsignhistory;
        pat = patient;
        
        patientnamejTextField.setText(patient.getPatientName());
        patientidjTextField.setText(patient.getPatentId());
        agejTextField.setText(String.valueOf(patient.getAge()));
        doctornamejTextField.setText(patient.getDoctorName());
        pharmacyjTextField.setText(patient.getPharmacy());
        age = patient.getAge();
        populatetable();
        resetFields();
        
    }

    public String agecheck()
    {
        if(age>=1 && age<=3)
            return "Toddler";
        else if (age>=4 && age<=5)
            return "Preschoorer";
        else if (age>=6 && age<=12)
            return "SchoolAge";
        else return "Adolescent";
    }
        
    public String healthconditions(int respR,int heartR, int bpR, int weightR )
    {
        
        Integer[] values = setdatarange(agecheck());
        boolean resprate = state(values,respR,0,1);
        boolean heartrate = state(values,heartR,2,3); 
        boolean Bloodpressure = state(values,bpR,4,5);
        boolean weight = state(values,weightR,6,7);
        
        if (resprate && heartrate && Bloodpressure && weight)
                return "Normal";
        else
            return "Abnormal";
    }
    
    public Integer[] setdatarange(String agegroup)
    {
        Integer[] xx={0};
        TreeMap<String, Integer[]> map = new TreeMap<>();
        map.put("Toddler", new Integer[] {20,30,80,130,80,110,22,31});
        map.put("Preschoorer", new Integer[] {20,30,80,120,80,110,31,40});
        map.put("SchoolAge", new Integer[] {20,30,70,110,80,120,41,92});
        map.put("Adolescent",new Integer[] {12,20,55,105,110,120,110,100000});
        
        if (map.containsKey(agegroup)){
             xx = map.get(agegroup);
             return xx;
        }
        return xx;
    }
    
    public boolean state(Integer[] x,int vitalvalue,int first,int last)
    {
    int[] valuerange = IntStream.rangeClosed(x[first], x[last]).toArray();
    ArrayList<Integer> patientlist = new ArrayList<>();
    for (int i=0;i<valuerange.length;i++)
          patientlist.add(valuerange[i]);
     if (patientlist.contains(vitalvalue))
            return true;
     else
            return false;
    }
    
    public void populatetable() {
    
        DefaultTableModel dtm = (DefaultTableModel)detailsjTable.getModel();
        int rowcount = detailsjTable.getRowCount();
                
                
        for ( int i= rowcount -1 ; i>=0; i--)
            dtm.removeRow(i);
        
        for (VitalSign vs : vitalsignhistory.getVitalSignList())
        {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = healthconditions(vs.getRespiratoryRate(),vs.getHeartRate(),vs.getBloodPressure(),vs.getWeight());
            dtm.addRow(row);
        }
        
}
    public void resetFields(){
    
    bloodpressurejTextField.setText("");
    heartratejTextField.setText("");
    respiratoryratejTextField.setText("");
    datejTextField.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsjTable = new javax.swing.JTable();
        viewdetailsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        respiratoryratejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        heartratejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bloodpressurejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        weightjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        datejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        patientnamejTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        patientidjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        agejTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        doctornamejTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pharmacyjTextField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View patient details");

        detailsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Condition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(detailsjTable);
        if (detailsjTable.getColumnModel().getColumnCount() > 0) {
            detailsjTable.getColumnModel().getColumn(0).setResizable(false);
        }

        viewdetailsBtn.setText("View Details");
        viewdetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Respiratory Rate");

        jLabel3.setText("Heart Rate");

        jLabel4.setText("Systolic Blood Pressure");

        jLabel5.setText("Weight(Pounds)");

        jLabel6.setText("Date");

        datejTextField.setEditable(false);
        datejTextField.setBackground(new java.awt.Color(204, 204, 204));
        datejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datejTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Patient Name");

        patientnamejTextField.setEditable(false);
        patientnamejTextField.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Patient ID");

        patientidjTextField.setEditable(false);
        patientidjTextField.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Age");

        agejTextField.setEditable(false);
        agejTextField.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Doctor Name");

        doctornamejTextField.setEditable(false);
        doctornamejTextField.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pharmacy");

        pharmacyjTextField.setEditable(false);
        pharmacyjTextField.setBackground(new java.awt.Color(204, 204, 204));

        deleteBtn.setText("Delete Button");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(139, 139, 139)
                                .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(141, 141, 141)
                                    .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bloodpressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(136, 136, 136)
                                .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(107, 107, 107))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(viewdetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteBtn)
                                    .addComponent(respiratoryratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewdetailsBtn)
                            .addComponent(deleteBtn))
                        .addGap(77, 77, 77)))
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(patientnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(respiratoryratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel3))
                        .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(bloodpressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(datejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsBtnActionPerformed
        
        int selectedrow = detailsjTable.getSelectedRow();
        if(selectedrow >=0)
        {
            VitalSign vs = (VitalSign) detailsjTable.getValueAt(selectedrow,0);
            respiratoryratejTextField.setText(String.valueOf(vs.getRespiratoryRate()));
            heartratejTextField.setText(String.valueOf(vs.getHeartRate()));
            bloodpressurejTextField.setText(String.valueOf(vs.getBloodPressure()));
            datejTextField.setText(String.valueOf(vs.getTime()));
            weightjTextField.setText(String.valueOf(vs.getWeight()));
            } else {
           
            JOptionPane.showMessageDialog(this, "Please select a row","Warning", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_viewdetailsBtnActionPerformed

    private void datejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datejTextFieldActionPerformed
        
    }//GEN-LAST:event_datejTextFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        int selectedrow = detailsjTable.getSelectedRow();
        if (selectedrow >=0)
        {
            int dialogue = JOptionPane.YES_NO_OPTION;
            int dialogueresult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete","Warning",dialogue);
            if (dialogueresult == JOptionPane.YES_OPTION)
            {
            VitalSign vs = (VitalSign) detailsjTable.getValueAt(selectedrow, 0);
            vitalsignhistory.deleteVitalsign(vs);
            populatetable();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row","Warning", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agejTextField;
    private javax.swing.JTextField bloodpressurejTextField;
    private javax.swing.JTextField datejTextField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable detailsjTable;
    private javax.swing.JTextField doctornamejTextField;
    private javax.swing.JTextField heartratejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientidjTextField;
    private javax.swing.JTextField patientnamejTextField;
    private javax.swing.JTextField pharmacyjTextField;
    private javax.swing.JTextField respiratoryratejTextField;
    private javax.swing.JButton viewdetailsBtn;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
