/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MainMenu;

import Business.Customer;
import Business.Product;
import Business.ProductCatalog;
import Business.CustomerDirectory;
import Business.SalesDirectory;
import Business.supplierdirectory;
import UserInterface.Administrator.AdminOptions;
import UserInterface.Salesperson.Transaction;
import UserInterface.Salesperson.report;
import UserInterface.Supplier.Supplieroption;
import java.awt.CardLayout;
import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author Vivek
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private SalesDirectory salesdirectory;
    private supplierdirectory SupplierDirectory;
    private ProductCatalog productcatalog;
    private CustomerDirectory customerdirectory;
    
    public MainJFrame() {
        initComponents();
        productcatalog = new ProductCatalog();
        salesdirectory = new SalesDirectory();
        SupplierDirectory = new supplierdirectory();
        customerdirectory = new CustomerDirectory();
        setSize(800, 610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        supplierjButton = new javax.swing.JButton();
        salesjButton = new javax.swing.JButton();
        administratorjButton = new javax.swing.JButton();
        populatedata = new javax.swing.JButton();
        reportjButton = new javax.swing.JButton();
        userprocesscontrol = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supplierjButton.setText("Supplier");
        supplierjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierjButtonActionPerformed(evt);
            }
        });

        salesjButton.setText("Sales");
        salesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesjButtonActionPerformed(evt);
            }
        });

        administratorjButton.setText("Administrator");
        administratorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administratorjButtonActionPerformed(evt);
            }
        });

        populatedata.setText("Populate Data");
        populatedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populatedataActionPerformed(evt);
            }
        });

        reportjButton.setText("Report");
        reportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(populatedata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administratorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(administratorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(supplierjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(salesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(populatedata, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(reportjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userprocesscontrol.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userprocesscontrol);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void administratorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administratorjButtonActionPerformed
        
    AdminOptions aop = new AdminOptions(userprocesscontrol,salesdirectory,SupplierDirectory,productcatalog);
    userprocesscontrol.add("AdminOptions", aop);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_administratorjButtonActionPerformed

    private void supplierjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierjButtonActionPerformed
        
    Supplieroption sop = new Supplieroption(userprocesscontrol,productcatalog);
    userprocesscontrol.add("AdminOptions", sop);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_supplierjButtonActionPerformed

    private void salesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesjButtonActionPerformed
        
    Transaction tr = new Transaction(userprocesscontrol,salesdirectory,productcatalog,customerdirectory);
    userprocesscontrol.add("Transaction", tr);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);

    }//GEN-LAST:event_salesjButtonActionPerformed

    private void populatedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populatedataActionPerformed
        
        populateproduct();
        populatecustomer();
        
        
    }//GEN-LAST:event_populatedataActionPerformed

    private void reportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportjButtonActionPerformed
        
    report Rep = new report(userprocesscontrol,salesdirectory,productcatalog,customerdirectory);
    userprocesscontrol.add("Report", Rep);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);

        
    }//GEN-LAST:event_reportjButtonActionPerformed

    public void populateproduct(){
    
        try {

         
	File fXmlFile = new File("C:\\Users\\Vivek\\Documents\\NetBeansProjects\\Assignment5\\src\\Business\\Data\\productdata.xml");
	DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
	DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
	Document doc = dBuilder.parse(fXmlFile);
		
          
	doc.getDocumentElement().normalize();
        NodeList nList = doc.getElementsByTagName("product");

        for (int temp = 0; temp < nList.getLength(); temp++) {
                Product product = productcatalog.addProduct();
                
		Node nNode = nList.item(temp);
			
		if (nNode.getNodeType() == Node.ELEMENT_NODE) {

                       Element eElement = (Element) nNode;
                       product.setProdName(eElement.getElementsByTagName("productname").item(0).getTextContent());
                       product.setCelingprice(Float.parseFloat(eElement.getElementsByTagName("ceilingprice").item(0).getTextContent()));
                       product.setFloorprice(Float.parseFloat(eElement.getElementsByTagName("floorprice").item(0).getTextContent()));
                       product.setTargetprice(Float.parseFloat(eElement.getElementsByTagName("targetprice").item(0).getTextContent()));
                       product.setQuantity(Integer.parseInt(eElement.getElementsByTagName("quantity").item(0).getTextContent()));
                     
		}
                System.out.println(product.getQuantity());
	}   
        
    } catch (Exception e) {
	e.printStackTrace();
    }}
    
    
    public void populatecustomer(){
    
        try {

         
	File fXmlFile = new File("C:\\Users\\Vivek\\Documents\\NetBeansProjects\\Assignment5\\src\\Business\\Data\\customerdata.xml");
	DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
	DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
	Document doc = dBuilder.parse(fXmlFile);
		
          
	doc.getDocumentElement().normalize();
        NodeList nList = doc.getElementsByTagName("customer");

        for (int temp = 0; temp < nList.getLength(); temp++) {
                Customer cust = customerdirectory.addCustomer();
		Node nNode = nList.item(temp);
				
		if (nNode.getNodeType() == Node.ELEMENT_NODE) {

                       Element eElement = (Element) nNode;
                       cust.setCustomerId(Integer.parseInt(eElement.getAttribute("id")));
                       cust.setCustomerName(eElement.getElementsByTagName("customername").item(0).getTextContent());
                       
                       System.out.println(cust.getCustomerId()+","+cust.getCustomerName());
                }
	}
            
        
    } catch (Exception e) {
	e.printStackTrace();
    }}
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administratorjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton populatedata;
    private javax.swing.JButton reportjButton;
    private javax.swing.JButton salesjButton;
    private javax.swing.JButton supplierjButton;
    private javax.swing.JPanel userprocesscontrol;
    // End of variables declaration//GEN-END:variables
}
