/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CvsAdmin;

import UserInterface.Store.StoreoptionjPanel;
import Business.DrugInventory;
import Business.StoreDirectory;
import Business.supplierdirectory;
import UserInterface.Supplier.SupplierOptionPage;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class cvsadminoptionpage extends javax.swing.JPanel {

    /**
     * Creates new form cvsadminoptionpage
     */
    private JPanel userprocesscontrol;
    DrugInventory druginventory;
    StoreDirectory storedirectory;
    supplierdirectory SupplierDirectory;
    
    public cvsadminoptionpage(JPanel userprocesscontrol,DrugInventory druginventory, StoreDirectory storedirectory,supplierdirectory SupplierDirectory) {
        initComponents();
        this.userprocesscontrol = userprocesscontrol;
        this.druginventory = druginventory;
        this.storedirectory = storedirectory;
        this.SupplierDirectory = SupplierDirectory;        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageDrugjButton = new javax.swing.JButton();
        createStoresjButton = new javax.swing.JButton();
        browseStorejButton = new javax.swing.JButton();
        supplierjButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        manageDrugjButton.setText("Manage Drug catalog");
        manageDrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDrugjButtonActionPerformed(evt);
            }
        });

        createStoresjButton.setText("Create Stores");
        createStoresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStoresjButtonActionPerformed(evt);
            }
        });

        browseStorejButton.setText("Browse Stores");
        browseStorejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseStorejButtonActionPerformed(evt);
            }
        });

        supplierjButton.setText("Add Supplier");
        supplierjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createStoresjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(browseStorejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(manageDrugjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(manageDrugjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createStoresjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(browseStorejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void manageDrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDrugjButtonActionPerformed
        
    ManageDrugCatalogjPanel mdcp = new ManageDrugCatalogjPanel(userprocesscontrol,druginventory,SupplierDirectory);
    userprocesscontrol.add("ManageDrugCatalogjPanel", mdcp);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
        
        
    }//GEN-LAST:event_manageDrugjButtonActionPerformed

    private void createStoresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStoresjButtonActionPerformed
        
    StoreoptionjPanel csp = new StoreoptionjPanel(userprocesscontrol,druginventory , storedirectory);
    userprocesscontrol.add("CreateStorejPanel", csp);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_createStoresjButtonActionPerformed

    private void browseStorejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseStorejButtonActionPerformed
   
    BrowseCatalogJPanel bcp = new BrowseCatalogJPanel(userprocesscontrol,druginventory , storedirectory);
    userprocesscontrol.add("BrowseCatalogJPanel", bcp);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
    }//GEN-LAST:event_browseStorejButtonActionPerformed

    private void supplierjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierjButtonActionPerformed
        
    SupplierOptionPage sop = new SupplierOptionPage(userprocesscontrol,druginventory , storedirectory,SupplierDirectory);
    userprocesscontrol.add("SupplierOptionPage", sop);
    CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
    layout.next(userprocesscontrol);
        
        
        
    }//GEN-LAST:event_supplierjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseStorejButton;
    private javax.swing.JButton createStoresjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageDrugjButton;
    private javax.swing.JButton supplierjButton;
    // End of variables declaration//GEN-END:variables
}
