/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdmin;

import Business.CVSStores;
import Business.DrugInventory;
import Business.Drugs;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class AdddrugtoList extends javax.swing.JPanel {

    /**
     * Creates new form AdddrugtoList
     */
     private JPanel userProcessContainer;
     private CVSStores singlestore;
     DrugInventory druginventory;
     DrugInventory storedruginventory;
             
    public AdddrugtoList(JPanel userProcessContainer,DrugInventory druginventory, CVSStores store) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.singlestore = store;
        this.druginventory = druginventory;
        populatecvsdrugtable();
        populatesuppliertable();
    }

    public void populatecvsdrugtable(){
    
    DefaultTableModel dtm = (DefaultTableModel)drugjTable.getModel();
        int rowcount = drugjTable.getRowCount();
                
                
        for ( int i= rowcount -1 ; i>=0; i--)
            dtm.removeRow(i);
        
            for(Drugs drug : druginventory.getdrugsDir()){
                       Object []obj = new Object[4];
                       obj[0] = drug;
                       obj[1] = drug.getDrugname();
                       obj[2] = drug.getQuantity();
                       obj[3] = drug.getprice();
                       dtm.addRow(obj);
            }
    }
    
    public void populatesuppliertable(){
    
    DefaultTableModel dtm = (DefaultTableModel)suppliertable.getModel();
        int rowcount = suppliertable.getRowCount();
                
                
        for ( int i= rowcount -1 ; i>=0; i--)
            dtm.removeRow(i);
        
            for(Drugs dr : singlestore.getdrugcatalog().getdrugsDir())
            {
                       Object []obj = new Object[4];
                       obj[0] = dr;
                       obj[1] = dr.getDrugname();
                       obj[2] = dr.getQuantity();
                       obj[3] = dr.getprice()*dr.getQuantity();
                       dtm.addRow(obj);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppliertable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        setquantityjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        serialnumberjTextField = new javax.swing.JTextField();
        expirationjTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        drugjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drugjTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CVS inventory list");

        jButton1.setText("Add to store's list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        suppliertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug name", "Quantity", "Total Price "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(suppliertable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Set Quantity :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Set serial number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Expiration date");

        serialnumberjTextField.setEditable(false);
        serialnumberjTextField.setBackground(new java.awt.Color(204, 204, 204));

        expirationjTextField.setEditable(false);
        expirationjTextField.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serialnumberjTextField)
                            .addComponent(setquantityjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(expirationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton2)
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(294, 294, 294))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(setquantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(expirationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serialnumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int oldvalue,newvalue;
        boolean flag = true;
        int cvsselectedrow = drugjTable.getSelectedRow();
        Drugs drug = (Drugs) drugjTable.getValueAt(cvsselectedrow,0);
        
        DefaultTableModel dtm = (DefaultTableModel)suppliertable.getModel();
        int rowcount = suppliertable.getRowCount();
                
        for ( int i= rowcount -1 ; i>=0; i--)
            dtm.removeRow(i);
            
        for (Drugs dru: singlestore.getdrugcatalog().getdrugsDir())
        {
                if(dru.getDrugname().equals(drug.getDrugname()))
                {
                         oldvalue = dru.getQuantity();
                         newvalue = oldvalue+Integer.parseInt(setquantityjTextField.getText());
                         dru.setQuantity(newvalue);
                         flag = false;
                         break;
                }               
        }
        
        if(flag){
                
                Drugs storedrug = singlestore.getdrugcatalog().adddrug();
                storedrug.setDrugname(drug.getDrugname());
                storedrug.setDrugserialnumber(drug.getDrugserialnumber());
                storedrug.setQuantity(Integer.parseInt(setquantityjTextField.getText()));
                storedrug.setprice(drug.getprice());
                storedrug.setDrugserialnumber(serialnumberjTextField.getText());
                storedrug.setExpirydate(expirationjTextField.getText());
        }
        
        for(Drugs dr : singlestore.getdrugcatalog().getdrugsDir())
        {
                       Object []obj = new Object[4];
                       obj[0] = dr;
                       obj[1] = dr.getDrugname();
                       obj[2] = dr.getQuantity();
                       obj[3] = dr.getprice()*dr.getQuantity();
                       dtm.addRow(obj);
        }
        int recentvalue = drug.getQuantity() - Integer.parseInt(setquantityjTextField.getText());
        drug.setQuantity(recentvalue);
        setquantityjTextField.setText("");
        populatecvsdrugtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void drugjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugjTableMouseClicked
        
        int cvsselectedrow = drugjTable.getSelectedRow();
        Drugs drug = (Drugs) drugjTable.getValueAt(cvsselectedrow,0);
        
        serialnumberjTextField.setText(drug.getDrugserialnumber());
        expirationjTextField.setText(drug.getExpirydate());
    }//GEN-LAST:event_drugjTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable drugjTable;
    private javax.swing.JTextField expirationjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField serialnumberjTextField;
    private javax.swing.JTextField setquantityjTextField;
    private javax.swing.JTable suppliertable;
    // End of variables declaration//GEN-END:variables
}
