/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdmin;

import Business.CVSStores;
import UserInterface.StoreAdmin.AdddrugtoList;
import Business.DrugInventory;
import Business.StoreDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class storeAdminOptionjPanel extends javax.swing.JPanel {

    /**
     * Creates new form storeAdminOptionjPanel
     */
    private JPanel userprocesscontrol;
    DrugInventory druginventory;
    StoreDirectory storedirectory;

    public storeAdminOptionjPanel(JPanel userprocesscontrol,DrugInventory druginventory ,StoreDirectory storedirectory) {
        initComponents();
        this.userprocesscontrol = userprocesscontrol;
        this.druginventory = druginventory;
        this.storedirectory = storedirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adddrugsjbutton = new javax.swing.JButton();
        generatereportjButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        adddrugsjbutton.setText("Add Drugs");
        adddrugsjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddrugsjbuttonActionPerformed(evt);
            }
        });

        generatereportjButton.setText("Generate Report");
        generatereportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatereportjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generatereportjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adddrugsjbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(adddrugsjbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(generatereportjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void adddrugsjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddrugsjbuttonActionPerformed
        
        SelectStorejPanel ssp = new SelectStorejPanel(userprocesscontrol,druginventory ,storedirectory);
        userprocesscontrol.add("SelectStorejPanel", ssp);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.next(userprocesscontrol);
    }//GEN-LAST:event_adddrugsjbuttonActionPerformed

    private void generatereportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatereportjButtonActionPerformed
        
        ReportSelectStorejPanel ssp = new ReportSelectStorejPanel(userprocesscontrol,druginventory ,storedirectory);
        userprocesscontrol.add("SelectStorejPanel", ssp);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_generatereportjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddrugsjbutton;
    private javax.swing.JButton generatereportjButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
