/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.DrugInventory;
import Business.Drugs;
import Business.supplier;
import Business.supplierdirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class drugadditionbysupplier extends javax.swing.JPanel {

    /**
     * Creates new form drugadditionbysupplier
     */
    private JPanel userprocesscontrol;
    DrugInventory druginventory;
    supplier Supplier;
    int earliervalue;
    int newvalue;
    public drugadditionbysupplier(JPanel userprocesscontrol,DrugInventory druginventory, supplier Supplier) {
        initComponents();
        this.userprocesscontrol = userprocesscontrol;
        this.druginventory = druginventory;
        this.Supplier = Supplier;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drugwuantityjTextField = new javax.swing.JTextField();
        drugnamejTextField = new javax.swing.JTextField();
        drugserialnumberjTextField = new javax.swing.JTextField();
        manudatejTextField = new javax.swing.JTextField();
        expdatejTextField = new javax.swing.JTextField();
        drugpricejTextField = new javax.swing.JTextField();
        volumejTextField = new javax.swing.JTextField();
        legaljTextField = new javax.swing.JTextField();
        weightjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        submitjButton = new javax.swing.JButton();
        newvaluejTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add drugs");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Drug Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DrugSerialNumber");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Manufacture date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Expiry date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Volumne Intake");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Legal");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Weight");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        newvaluejTextField.setEditable(false);
        newvaluejTextField.setText("New quantity");

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugpricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expdatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitjButton)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugserialnumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manudatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(legaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drugwuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(newvaluejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 87, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drugnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newvaluejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(drugwuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drugserialnumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(manudatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(expdatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(drugpricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(volumejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(legaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitjButton)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean flag = true;
        for(Drugs drug : druginventory.getdrugsDir()){
                if(drugnamejTextField.getText().equals(drug.getDrugname())){
                    newvaluejTextField.setEditable(true);
                    newvaluejTextField.setText("");
                    drugnamejTextField.setText(drug.getDrugname());
                    drugnamejTextField.setEnabled(false);
                    drugwuantityjTextField.setText(String.valueOf(drug.getQuantity()));
                    drugwuantityjTextField.setEnabled(false);
                    drugpricejTextField.setText(String.valueOf(drug.getprice()));
                    drugpricejTextField.setEnabled(false);
                    drugserialnumberjTextField.setText(String.valueOf(drug.getDrugserialnumber()));
                    drugserialnumberjTextField.setEnabled(false);
                    expdatejTextField.setText(String.valueOf(drug.getExpirydate()));
                    expdatejTextField.setEnabled(false);
                    legaljTextField.setText(drug.getExpirydate());
                    legaljTextField.setEnabled(false);
                    manudatejTextField.setText(drug.getManufacturedate());
                    manudatejTextField.setEnabled(false);
                    volumejTextField.setText(String.valueOf(drug.getVolumeintake()));
                    volumejTextField.setEnabled(false);
                    weightjTextField.setText(String.valueOf(drug.getWeight()));
                    weightjTextField.setEnabled(false);
                    earliervalue = drug.getQuantity();
                    flag = false;
                    break;
                }}
                    if(flag)
                    JOptionPane.showMessageDialog(this, "No drug found in drug directory.","Warning",JOptionPane.WARNING_MESSAGE);
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        boolean flag = true;

        for(Drugs drug : druginventory.getdrugsDir())
        {
             if(drugnamejTextField.getText().equals(drug.getDrugname())){
                 newvalue = earliervalue + Integer.parseInt(newvaluejTextField.getText()) ;
                 drug.setQuantity(newvalue);
                 flag = false;
                 break;
             }
        } 
        enabletextfields();
        
        if(flag){            
                
                Drugs drugx = druginventory.adddrug();
                drugx.setDrugname(drugnamejTextField.getText());
                drugx.setQuantity(Integer.parseInt(drugwuantityjTextField.getText()));
                drugx.setDrugserialnumber(drugserialnumberjTextField.getText());
                drugx.setprice(Integer.parseInt(drugpricejTextField.getText()));
                drugx.setExpirydate(expdatejTextField.getText());
                drugx.setLeagal(legaljTextField.getText());
                drugx.setManufacturedate(manudatejTextField.getText());
                drugx.setVolumeintake(Integer.parseInt(volumejTextField.getText()));
                drugx.setWeight(Integer.parseInt(weightjTextField.getText()));
                }
        JOptionPane.showMessageDialog(this, "Drug added!!");
         clearfieldvalue();
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        userprocesscontrol.remove(this);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.previous(userprocesscontrol);        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void enabletextfields(){
                    drugnamejTextField.setEnabled(true);
                    drugwuantityjTextField.setEnabled(true);
                    drugpricejTextField.setEnabled(true);
                    drugserialnumberjTextField.setEnabled(true);
                    expdatejTextField.setEnabled(true);
                    legaljTextField.setEnabled(true);
                    manudatejTextField.setEnabled(true);
                    volumejTextField.setEnabled(true);
                    weightjTextField.setEnabled(true);
    }             
     public void clearfieldvalue(){             
                    
        drugnamejTextField.setText("");
        drugwuantityjTextField.setText("");
        drugpricejTextField.setText("");
        drugserialnumberjTextField.setText("");
        expdatejTextField.setText("");
        legaljTextField.setText("");
        manudatejTextField.setText("");
        newvaluejTextField.setText("");
        volumejTextField.setText("");
        weightjTextField.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drugnamejTextField;
    private javax.swing.JTextField drugpricejTextField;
    private javax.swing.JTextField drugserialnumberjTextField;
    private javax.swing.JTextField drugwuantityjTextField;
    private javax.swing.JTextField expdatejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField legaljTextField;
    private javax.swing.JTextField manudatejTextField;
    private javax.swing.JTextField newvaluejTextField;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField volumejTextField;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
