/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Patient;

import com.Business.Person;
import com.Business.VitalSign;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class UpdatejPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatejPanel
     */
    
    JPanel userprocesscontrol;
    VitalSign vitalsign;
    AddVitalSignForm vitalsignform;
    
    public UpdatejPanel(JPanel upc,VitalSign per,AddVitalSignForm ma) {
        initComponents();
        this.userprocesscontrol = upc;
        this.vitalsign = per;
        this.vitalsignform = ma;
        populatetexts();
    }

    public void populatetexts(){
        
            respiratoryratejTextField.setText(String.valueOf(vitalsign.getRespiratoryRate()));            
            heartratejTextField.setText(String.valueOf(vitalsign.getRespiratoryRate()));
            bloodpressurejTextField.setText(String.valueOf(vitalsign.getBloodPressure()));
            weightjTextField.setText(String.valueOf(vitalsign.getWeight()));            
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        respiratoryratejTextField = new javax.swing.JTextField();
        heartratejTextField = new javax.swing.JTextField();
        bloodpressurejTextField = new javax.swing.JTextField();
        weightjTextField = new javax.swing.JTextField();
        SavejButton = new javax.swing.JButton();
        UpdatejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Update ");

        jLabel2.setText("Respiratory Rate");

        jLabel3.setText("Heart Rate");

        jLabel4.setText("Systolic Blood Pressure");

        jLabel5.setText("Weight(Pounds)");

        respiratoryratejTextField.setEditable(false);
        respiratoryratejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                respiratoryratejTextFieldKeyTyped(evt);
            }
        });

        heartratejTextField.setEditable(false);
        heartratejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heartratejTextFieldKeyTyped(evt);
            }
        });

        bloodpressurejTextField.setEditable(false);
        bloodpressurejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bloodpressurejTextFieldKeyTyped(evt);
            }
        });

        weightjTextField.setEditable(false);
        weightjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightjTextFieldKeyTyped(evt);
            }
        });

        SavejButton.setText("Save");
        SavejButton.setEnabled(false);
        SavejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButtonActionPerformed(evt);
            }
        });

        UpdatejButton.setText("Update");
        UpdatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatejButtonActionPerformed(evt);
            }
        });

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(SavejButton)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdatejButton)
                            .addComponent(respiratoryratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodpressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(backjButton)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(respiratoryratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bloodpressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavejButton)
                    .addComponent(UpdatejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(55, 55, 55))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void respiratoryratejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respiratoryratejTextFieldKeyTyped
        char respiratory = evt.getKeyChar();
        if (!(Character.isDigit(respiratory)))
        evt.consume();
    }//GEN-LAST:event_respiratoryratejTextFieldKeyTyped

    private void heartratejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heartratejTextFieldKeyTyped
        char heartrate = evt.getKeyChar();
        if (!(Character.isDigit(heartrate)))
        evt.consume();
    }//GEN-LAST:event_heartratejTextFieldKeyTyped

    private void bloodpressurejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bloodpressurejTextFieldKeyTyped
        char bloodpressure = evt.getKeyChar();
        if (!(Character.isDigit(bloodpressure)))
        evt.consume();
    }//GEN-LAST:event_bloodpressurejTextFieldKeyTyped

    private void weightjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightjTextFieldKeyTyped
        char weight = evt.getKeyChar();
        if (!(Character.isDigit(weight)))
        evt.consume();
    }//GEN-LAST:event_weightjTextFieldKeyTyped

    private void UpdatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatejButtonActionPerformed
        
        respiratoryratejTextField.setEditable(true);
        heartratejTextField.setEditable(true);
        bloodpressurejTextField.setEditable(true);
        weightjTextField.setEditable(true);
        SavejButton.setEnabled(true);
        UpdatejButton.setEnabled(false);
    }//GEN-LAST:event_UpdatejButtonActionPerformed

    private void SavejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejButtonActionPerformed
        
        vitalsign.setRespiratoryRate(Integer.parseInt(respiratoryratejTextField.getText()));
        vitalsign.setHeartRate(Integer.parseInt(heartratejTextField.getText()));
        vitalsign.setBloodPressure(Integer.parseInt(bloodpressurejTextField.getText()));
        vitalsign.setWeight(Integer.parseInt(weightjTextField.getText()));
               
        
    }//GEN-LAST:event_SavejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        
        userprocesscontrol.remove(this);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.previous(userprocesscontrol);
        vitalsignform.populatetable();
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SavejButton;
    private javax.swing.JButton UpdatejButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField bloodpressurejTextField;
    private javax.swing.JTextField heartratejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField respiratoryratejTextField;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
