/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Patient;

import com.Business.Patient;
import com.Business.Person;
import com.Business.PersonDirectory;
import com.Business.VitalSignHistory;
import com.Person.UpdatePerson;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivek
 */
public class addpatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form addpatientDetails
     */
    JPanel userprocesscontrol;
    VitalSignHistory vitalsignhistory;
    PersonDirectory persondirectory;
        
    public addpatientDetails(JPanel upc,VitalSignHistory vitalsignhistory,PersonDirectory pdir) {
        initComponents();
        this.userprocesscontrol = upc;
        this.persondirectory = pdir;
        populatetable();
    }

    
    public void populatetable(){
    
     DefaultTableModel dtm = (DefaultTableModel)personlistjTable.getModel();
        int rowcount = personlistjTable.getRowCount();
                
                
        for ( int i= rowcount -1 ; i>=0; i--)
            dtm.removeRow(i);
        
        for (Person per : persondirectory.getpersonlist())
        {
            Object row[] = new Object[3];
            row[0] = per;
            row[1] = per.getAge();
            row[2] = per.getMailid();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patientidjTextField = new javax.swing.JTextField();
        doctornamejTextField = new javax.swing.JTextField();
        pharmacynamejTextField = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personlistjTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Patient details");

        jLabel2.setText("Patient ID");

        jLabel3.setText("Doctor's Name");

        jLabel4.setText("Pharmacy Name");

        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        personlistjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PersonName", "Age", "mailId"
            }
        ));
        jScrollPane1.setViewportView(personlistjTable);
        if (personlistjTable.getColumnModel().getColumnCount() > 0) {
            personlistjTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Person List");

        updatejButton.setText("Update Person");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pharmacynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(updatejButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(backjButton)
                        .addGap(93, 93, 93)
                        .addComponent(addjButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(updatejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(patientidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addComponent(doctornamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pharmacynamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(addjButton))
                .addGap(22, 22, 22))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        
        userprocesscontrol.remove(this);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.previous(userprocesscontrol);
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        
        int selectedrow = personlistjTable.getSelectedRow();
        if(selectedrow >=0)
        {
            Person peeps = (Person) personlistjTable.getValueAt(selectedrow,0);
            if(track(peeps)){
            Patient patient = peeps.getvitalsignhistory().addPatient();
            String patient1 = patient.getPatientId();
            if((patient1 == null)){
                    patient.setPatientId(patientidjTextField.getText());
                    patient.setDoctorName(doctornamejTextField.getText());
                    patient.setPharmacy(pharmacynamejTextField.getText());
                JOptionPane.showMessageDialog(this, "Patient is added.","Information", JOptionPane.INFORMATION_MESSAGE);
                    
            } else {
                    JOptionPane.showMessageDialog(this, "Please select a row","Warning", JOptionPane.ERROR_MESSAGE);
        } }
            else{
                JOptionPane.showMessageDialog(this, "Patient details are already set.","Warning", JOptionPane.ERROR_MESSAGE);
                }
     } else {
            JOptionPane.showMessageDialog(this, "Please select a row","Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addjButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        
        int selectedrow = personlistjTable.getSelectedRow();
        if(selectedrow >=0)
        {
            Person person = (Person) personlistjTable.getValueAt(selectedrow,0);
            
            UpdatePerson va = new UpdatePerson(userprocesscontrol,person,this);
            userprocesscontrol.add("UpdatePerson",va);
            CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
            layout.next(userprocesscontrol);
        }  
        else {
            JOptionPane.showMessageDialog(this, "Please select a row","Warning", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_updatejButtonActionPerformed

    public boolean track(Person peeps)
    {
    ArrayList<Patient> List = peeps.getvitalsignhistory().getpatientList();
            if(List.isEmpty())
                return true;
            else 
                return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField doctornamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientidjTextField;
    private javax.swing.JTable personlistjTable;
    private javax.swing.JTextField pharmacynamejTextField;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
