/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Patient;

import com.Business.Person;
import com.Business.PersonDirectory;
import com.Business.VitalSignHistory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vivek
 */
public class PatientOption extends javax.swing.JPanel {

    /**
     * Creates new form PatientOption
     */
    private JPanel userprocesscontrol;
    private VitalSignHistory vitalSignHistory;
    PersonDirectory persondirectory;
    
    public PatientOption(JPanel upc,VitalSignHistory vitalSignHistory, PersonDirectory persondirectory) {
        initComponents();
        this.userprocesscontrol = upc;
        this.vitalSignHistory = vitalSignHistory;
        this.persondirectory = persondirectory;
        if(!(persondirectory.getpersonlist().isEmpty())){
          addpatientjButton.setEnabled(true);
        } 
        for (Person person : persondirectory.getpersonlist())
        {
             if (!(person.getvitalsignhistory().getpatientList().isEmpty()))
             {
                 addvitalsignjButton.setEnabled(true);
             }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addpatientjButton = new javax.swing.JButton();
        addvitalsignjButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        addpatientjButton.setText("Add patient details");
        addpatientjButton.setEnabled(false);
        addpatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientjButtonActionPerformed(evt);
            }
        });

        addvitalsignjButton.setText("Add vital signs");
        addvitalsignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvitalsignjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addpatientjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addvitalsignjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(addpatientjButton)
                .addGap(62, 62, 62)
                .addComponent(addvitalsignjButton)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addpatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientjButtonActionPerformed
        
        addpatientDetails apd = new addpatientDetails(userprocesscontrol,vitalSignHistory,persondirectory);
        userprocesscontrol.add("CreateVitalForm",apd);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_addpatientjButtonActionPerformed

    private void addvitalsignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvitalsignjButtonActionPerformed
        
        for (Person person : persondirectory.getpersonlist())
        {
             if (person.getvitalsignhistory().getpatientList().isEmpty())
             {
                 addvitalsignjButton.setEnabled(true);
             }
        }
        
        AddVitalSignForm avsf = new AddVitalSignForm(vitalSignHistory,userprocesscontrol,persondirectory);
        userprocesscontrol.add("AddVitalSignForm",avsf);
        CardLayout layout = (CardLayout) userprocesscontrol.getLayout();
        layout.next(userprocesscontrol);
        
    }//GEN-LAST:event_addvitalsignjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpatientjButton;
    private javax.swing.JButton addvitalsignjButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
